export const tasks = {
  GET_TASKS: "GET_TASKS",
  SET_TASKS_DATA: "SET_TASKS_DATA",
  OPEN_NEW_TASK_DIALOG: "OPEN_NEW_TASK_DIALOG",
  CLOSE_NEW_TASK_DIALOG: "CLOSE_NEW_TASK_DIALOG",
  OPEN_EDIT_TASK_DIALOG: "OPEN_EDIT_TASK_DIALOG",
  CLOSE_EDIT_TASK_DIALOG: "CLOSE_EDIT_TASK_DIALOG",
  LOAD_TASKS_START: "LOAD_TASKS_START",
  LOAD_TASKS_SUCCESS: "LOAD_TASKS_SUCCESS",
  SET_ERROR_LOGIN: "SET_ERROR_LOGIN",
  SET_IS_LOGIN: "SET_IS_LOGIN",
  SET_STATUS_NOTIFICATION: "SET_STATUS_NOTIFICATION"
};
